apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-clean-slate
  
message: A CronJob service has been created in your project. Its current schedule is ${CRON_SCHEDULE} and it will operate against the following DeploymentConfigs - ${DEPLOYMENT_CONFIGS}
  
parameters:
- name: JOB_NAME
  description: Unique identifier for this particular job
  displayName: Job Name
  value: clean-slate
  required: true  
- name: DEPLOYMENT_CONFIGS
  description: A comma-seperated list of Deployments to wipe clean on a scheduled basis
  displayName: Deployment Configs
  required: true
- name: CRON_SCHEDULE
  description: Standard Cron schedule against which to execute the job
  displayName: Cron Schedule
  value: "*/2 * * * *"
  required: true
  
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: openshift-clean-slate
      job: ${JOB_NAME}
    name: openshift-clean-slate
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: openshift-clean-slate:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/benemon/openshift-clean-slate
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel7-atomic:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: ${JOB_NAME}
    labels:
      job: ${JOB_NAME}
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
  spec:
    schedule: ${CRON_SCHEDULE}
    jobTemplate:             
      spec:
        template:
          metadata:
            labels:          
              parent: ${JOB_NAME}-parent
          spec:
            containers:
            - name: ${JOB_NAME}
              image: openshift-clean-slate:latest
              env:
              - name: DEPLOYMENT_CONFIGS
                valueFrom:
                  configMapKeyRef:
                    name: ${JOB_NAME}-config
                    key: deployment.configs              
            restartPolicy: OnFailure 

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: openshift-clean-slate
      job: ${JOB_NAME}
    name: openshift-clean-slate
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: openshift-clean-slate:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
    
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: openshift-clean-slate
      job: ${JOB_NAME}
    name: rhel7-atomic
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhel7-atomic
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel7-atomic:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
    
- apiVersion: v1
  data:
    deployment.configs: ${DEPLOYMENT_CONFIGS}
  kind: ConfigMap
  metadata:
    labels:
      job: ${JOB_NAME}
    name: ${JOB_NAME}-config
